# --- Build stage ---
FROM node:20 AS base

WORKDIR /app

ARG PRIVATE_ENCRYPTION_KEY

RUN npm install -g rimraf

COPY package*.json ./

RUN npm ci

COPY . .

# Build the app
RUN npm run build

# --- Runtime stage ---
FROM node:20-slim AS runtime

WORKDIR /app

COPY --from=base /app ./

EXPOSE 3000

RUN useradd -m appuser && chown -R appuser:appuser /app
USER appuser

ENTRYPOINT ["npm", "run", "start:local"]
